- _config.yml
- go
- pages/code-collaboration.md
- pages/code-review.md
More or less copy-pasted from CFPB's [version](https://github.com/cfpb/front-end/blob/master/code-reviews.md)
Also allows arguments to be passed to the `go` commands
> Initial Code Review Content

- _config.yml
- pages/workflows.md
@jessieay collected references to docs describing how several projects
submit/review code. This PR puts them in our development guide.
> Add "Example Workflows" page

- README.md
- ruby/.rubocop.yml
- ruby/README.md
**Why**: To get a new Ruby section started and a discussion on our
recommended Rubocop configuration.
> Begin work on Ruby Guide with Rubocop template

- README.md
- language_selection.md
- language_selection/README.md
We held a "best practices" discussion with roughly a dozen developers last
week, focused on language selection. This document is rooted in the notes from
that discussion, but has been elaborated to provide more concise guidance.
> First draft at language selection guidance

- people/2016-Assessment-Guide.md
Moving the Engineering 2016 End of Year Assessment Guide out of google docs into github.
> Creating End of Year Assessment Guide

- README.md
- accessibility_scanning/README.md
As outlined in the following PR/issue  https://github.com/18F/18f.gsa.gov/pull/1924 by the 18f-site team.
> add guide to setup accessibility scanning on local machine or CircleCI

- project_setup/README.md
We're about to start building out default project templates, so I've written
this little checklist to get us started. It doesn't go into detail (that can
come later) and focuses only on initialization (so it doesn't cover things
like DAP setup, etc.), but are there other important setup details missing?
> Add a VERY rough first draft of an init checklist

- example_workflows/README.md
Also, fix some broken links.
/cc @cmc333333 @yozlet
> link to additional workflow documents

- accessibility_scanning/README.md
Specify the need for the ACCESSLINT_GITHUB_USER token, and fix the Gemfile text.
> Make some corrections to ensure this will work

- project_setup/README.md
- project_setup/docker/README.md
Goal here is to help get folks started on using Docker for development.
Unfortunately, we don't have a cookie-cutter template for this sort of thing,
so it's less comprehensive than I'd like. It does try to add some fencing
(e.g. use docker-compose, here are some options for one-off commands, etc.)
and links to several projects.
Preview: https://github.com/18F/development-guide/tree/docker/project_setup/docker
> First draft of loose Docker guidelines/pointers.

- project_setup/README.md
Noting security concerns about localtunnel & ngrok. See https://github.com/18F/Infrastructure/issues/617 and https://github.com/18F/Infrastructure/issues/583 for more context if needed.
> forbidding localtunnel/ngrok as per infra issue 617

- code_review/README.md
As I was reviewing the material, I noticed a duplicate word.
> Small change to remove extra word

- python/README.md
Changes `for ensure consistency` to `for ensuring consistency`.
> Fix a minor typo

- tech_leads/README.md
Welcome @jeremiak, new front end lead!
> Add Jeremia

- tech_leads/README.md
We've got a new batch! Note that this doesn't include Diversity Lead at the moment; I assume the API there will continue to be rather different.
> Update tech leads

- python/README.md
> Fix typo in README.md

- continuous_deployment/README.md
Looks like I was too quick to close off https://github.com/18F/development-guide/pull/87. 18F transitioned off Travis around tail end of 2017 and was removed from the approved list of software in GEAR at that time.
Removing all Travis references from the continuous deploy README.
> Removing Travis references entirely

- README.md
- _config.yml
Clarify that guild is TTS, sync front matter with guild charter text, improve overview.
> Clarify TTS-wide nature of guild, sync with charter

- Dockerfile
- docker-compose.yml
Copied the Dockerfile and docker-compose from the handbook, since that seemed easy. And it worked! 🎉
- closes #103
> Dockerize the guide

- _pages/integrations.md
- _pages/project-setup.md
> Minor content corrections

- _includes/components/tag-caution.html
- _pages/index.md
Cherry-picking Greg's caution tag from #134 so we can start using it in the #124 content sweep.
> Add caution tag

- _pages/index.md
- _pages/workflow.md
> Updates to workflow page

- _pages/integrations.md
> Updates to 3rd party integrations

- _pages/project-setup.md
Pervasive use of classification tags where products/tools are mentioned, generous sprinkling of URLs, removed link to unmaintained 18f-scaffolding, clarified Docker use, applied partial order to checklist items, removed products no longer in use.
> Updates to project setup page

- _pages/crossbrowser-testing.md
- _pages/index.md
> Cross-browser testing write-up

- _pages/css/frameworks.md
- _pages/integrations.md
- _pages/language-selection.md
Closes https://github.com/18F/development-guide/issues/186.
> update list of third-party integrations

- _guide/_pages/accessibility-scanning.md
`ther` --> `other`
Thanks for maintaining this resource!
> Fix minor typo in accessibility-scanning.md

- _guide/_pages/browser-testing.md
Prompted by [recent Slack thread](https://gsa-tts.slack.com/archives/C039MHHF8/p1606244357307200)
> Clarify state of Cypress Test Runner and Dashboard

- _guide/_pages/continuous-deployment.md
Improved link text/usage in multiple places
> improve link text throughout document

- _guide/_pages/security/dependency-remediation.md
Remove question mark from the parenthetical in the last sentence so it reads as a statement.
> Remove question mark in dependency remediation

- _guide/_data/navigation.yml
- _guide/_pages/markdown.md
- _guide/_pages/python.md
- _guide/_pages/ruby.md
- _guide/_pages/workflow.md
> expand information about opinionated code styling

- README.md
- _guide/_pages/index.md
addresses #215 and also hopefully makes it nicer to contribute to the development guide!
> Add contributor blurb

- _guide/_pages/css/linting.md
> Remove Hound from guide

- _guide/_pages/code-review.md
I wondered if the existing language might accidentally encouraging efficiency at the margins, at the cost of readability, so I offer up this proposed change.
> Propose changing "as efficient as possible" to "reasonably efficient"

- _pages/workflow.md
Addresses #138. 
I also tried to clean up the page a bit to make it more readable and add classification tabs (which I could have sworn was an issue but I can't find it now.)
> Update secrets mgmt

- _pages/project-setup.md
Addresses #206 
I didn't put it in the config checklist because I wanted to add a little bit of explanation. Happy to fold it in if that seems off.
> Add link to branch protection rules documentation

- _pages/project-setup.md
> Add zenhub and jira to PM tools

- _data/navigation.yml
- _pages/release-strategies.md
> Add recommendations around reducing big bang release risk

- _pages/laptop-setup.md
- _pages/workflow.md
Part of https://github.com/18F/handbook/issues/2360
> Consolidate sensitive information guidance

- .github/workflows/pa11y.yml
Fixes GH workflows for future merges
> Fix: switch branch name in dependent gh workflow

- _pages/language-selection.md
Alternative can be "Lottery Problem" but the remaining text seems descriptive enough. I also added a comma.
> Avoid gratuitous references to violence

- _pages/code-review.md
Replace language referring to the default git branch
> Rename master to main

- _pages/resources.md
Before you ship guide is no more, adding consulting engineering guide and the 18F engineering field guide
> Add and fix links

- _pages/release-strategies.md
Closes issue #302 
Before You Ship now redirects to this page in the TTS handbook
> Link update

- _pages/css.md
> Updating Sass guidelines
