18F/development-guide

_config.yml
pages/git-protocol.md

* Makes the contents of the guide more intuitive
* Also removed some obviously non-applicable sections (eg: force pushing
/ rebasing are not common at 18F)

Rename `code-collaboration` to `git-protocol`

---

pages/code-review.md

This change set adds several additions to our code review documentation that expand on the following concepts:
- Benefits of code reviews
- What to look for when reviewing code
There are several document formatting updates and grammatical fixes made as well.

Update code review documentation with additional information

---

pages/code-review.md

* Until we develop a more streamlined set of recommendations, the code
review working group is going to work with product managers to get
each project team to have a discussion about code review.
* We will use the results of these conversations to create more
documentation and recommendations around "How 18F code reviews"

Add questions for "code review discussion"

---

pages/git-protocol.md

**Why**:
- Recommend setting up 2FA on GitHub
- Recommend signing commits with a GPG key
- Remove the section on merging since it contradicts how merges on GitHub work. GitHub uses `--no-ff` but the instructions were saying to use `--ff-only`. We typically use the GitHub web interface to merge, which is covered in the `Review Code` section, so I don't think we need an extra section on merging via the command line.

Update Git Protocol page

---

index.md

It seems the `index.md` was largely unmodified from the [guides template](https://pages.18f.gov/guides-template/), which made it rather confusing to read.
I'm not sure what best to put here, but I replaced it with something fairly minimal, so that it communicates the purpose of the guide without causing confusion. That said, I'm not 100% sure what the purpose of the guide *is*, so I guessed. Suggestions welcome!

Add introductory text to index.md

---

git_protocol/README.md

As I was re-writing a part of cloud.gov's FedRAMP documentation, I saw that [NIST 800-53 r4 SA-10.d](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=SA-10) requires that we
> Document approved changes to the system, component, or service and the potential security impacts of such changes
I could include this in cloud.gov documentation, but figured it was broadly-applicable enough to put in the 18F-wide guide.
/cc @brittag

Commit messages should include implications

---

ruby/.rubocop.yml

* This is a check that will help with upgrading to Ruby 3
* In the meantime, it is annoying
* Source https://github.com/bbatsov/rubocop/pull/2542

Disable `FrozenStringLiteralComment` cop

---

accessibility_scanning/README.md

This PR adds documentation to the accessibility scanning README, based on the recent, and successful addition of [AccessLintCI](https://github.com/accesslint/accesslint-ci/) to the 18f site repo with [this PR](https://github.com/18F/18f.gsa.gov/pull/2134).
cc @maya

Add accesslint documentation

---

accessibility_scanning/README.md

This PR updates the documentation for adding AccessLint to your repo.
It is based on a pairing session with @maya and @nickbristow to add accesslint to the 18F/accessibility repo, culminating in [**this PR**](https://github.com/18F/accessibility/pull/164). 
cc @maya

Update accesslint documentation

---

accessibility_scanning/README.md

This config file will not work (it'll generate an error about how Jekyll can't be found) without this step.

Fix example circle.yml

---

code_review/README.md

I see a preference at 18F to start PR's early in an issue's development, to simply start a conversation about the code — to share what we're doing with the rest of the team. I'm updating the text to reflect that.

Updating PR section for earlier creation

---

accessibility_scanning/README.md

I was following your instructions for accesslint and noticed an error. Since you're not installing accesslint-ci with bundler, you can't use `bundle exec` when executing it:
```
bundle exec accesslint-ci scan http://localhost:4000
bundler: failed to load command: accesslint-ci (/opt/circleci/.rvm/gems/ruby-2.3.1/bin/accesslint-ci)
Gem::LoadError: accesslint-ci is not part of the bundle. Add it to Gemfile.
/opt/circleci/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:351:in `block (2 levels) in replace_gem'
/opt/circleci/.rvm/gems/ruby-2.3.1/bin/accesslint-ci:22:in `<top (required)>'
bundle exec accesslint-ci scan http://localhost:4000 returned exit code 1
```
This PR fixes just by dropping the `bundle exec`.

Remove unnecessary bundle exec

---

nodejs/README.md

Here's an initial attempt at "codifying" some of the best practices for using Node.js at 18F. These include practices I see used in existing 18F projects and some practices I've used personally in the past. The goal is to document the current practices and opinions of those practices at 18F. A sub-goal is to serve as a place to have these kinds of conversations as the technology evolve and opinions shift.
This isn't a complete guide. I'm planning to add a few more PRs, but didn't want to get too far ahead of myself without getting some feedback.
The guide focuses on the 18F perspective, building applications for partners on cloud.gov which need to be ATO'd.
We don't have strong opinions on everything, so I wanted to differentiate "strongly recommended" vs things that seem to be working vs …

Add a nodejs language guide

---

tech_leads/README.md

We're using APIs as a metaphor for how 18F can engage with the technical leads, so the language should be consistent with that metaphor: the methods leads are offering, the responses callers can expect, how the services are billed, etc.

Establish Consistent API Metaphor Usage

---

tech_leads/README.md

The goal here is to document technical leads' responsibilities and spell out
some of the ways they achieve those objectives. Importantly, it should
encourage utilizing leads as a resource and downplay fears around additional
bureaucracy.
See [preview](https://github.com/18F/development-guide/tree/lead-api/tech_leads)

First draft of a technical leads API.

---

project_setup/README.md

Since Travis is no longer approved, removed from list of CI providers.
Resolves issue #59

Removed travis from list of CI providers

---

README.md
integrations/README.md

Having this initial list will help us standardize but also lets us determine which tools we need to train our engineers in.
[See it in action](https://github.com/18F/development-guide/tree/third-parties)
Note that despite the initial warning, some of these tools aren't completely through the IT Standards process. @hollyallen's said that's okay for now.

Initial list of default third parties to use.

---

README.md
workflow/README.md

This begins the process of consolidating several pages of recommendation while
aiming for concision.
[See it in action](https://github.com/18F/development-guide/tree/workflow-defaults)

Add initial set of defaults around workflow.

---

python/README.md

I thought they looked a little too cramped in a single paragraph, so split them out.

Move explanations of Standards/Defaults/Suggestions to separate paragraphs

---

README.md
python/README.md

This _largely_ encodes what we've seen across our current projects, but goes a
few steps beyond when making defaults and suggestions. Similar to the Node
guide, this breaks recommendations down into three levels of priority (though
it hopefully selects more meaningful terms).
See it [in action](https://github.com/18F/development-guide/tree/python-standards).

Add first draft of Python standards.

---

architecture_reviews/data_act_pilot/README.md
nodejs/README.md
polls/nodejs_for_backend_2016_12/README.md
polls/silos_and_soundness_2016_10/README.md
project_setup/README.md

This rewrites the Node guide to use the same terminology as the Python guide.
It removes a few conflicting suggestions (e.g. we now explicitly default to
Express over Hapi), duplicative advice (e.g. around 12-factor apps), condenses
library recommendations into a table, and pulls in some new content from #53.
[See it live](https://github.com/18F/development-guide/tree/node-standards/nodejs)

Rework Node to match Python; add new recs.

---

continuous_deployment/README.md

Noticed the continuous deployment's table of contents was linking to an old path.

Update continuous_deployment table of contents to link to relative sections

---

README.md
datastore_selection/README.md

Based on presentation and open discussion with the engineering chapter, we're
documenting our default to Postgres.
[Preview](https://github.com/18F/development-guide/tree/postgres/datastore_selection)

Add Datastore Selection Guidance.

---

nodejs/README.md

Hey, I fixed two spelling mistakes in the `NodeJS` docs.
- `stardards `-> `standards`
- `Github `-> `GitHub`

NodeJS docs: Grammar fix

---

continuous_deployment/README.md

This PR adds CircleCI example code for testing and deploying to Cloud.gov. ~~It's using the [CloudFoundry Orb](https://circleci.com/orbs/registry/orb/circleci/cloudfoundry) to hide most of the boilerplate code, just requiring the needed config variables.~~
The included example will run tests on all branches. The Cloud.gov deploy will only happen when the tests pass on the master branch.
~~I've included links in the comments to the documentation in case people want to implement blue green deploys.~~
Closes #86

Adds CircleCi examples for testing and deploying.

---

_pages/project-setup/docker.md

- Update the information about which CF root filesystem image to use, and be clear which Ubuntu version it corresponds to
- Link to community CF docs, rather than Pivotal's

Minor updates

---

.circleci/config.yml

Branch name is a misnomer – this addresses remaining items on #95 by incorporating the [CircleCI config from the TTS handbook](https://github.com/18F/handbook/blob/master/.circleci/config.yml).

Copy and tweak CircleCI config from TTS handbook

---

.circleci/config.yml
_config.yml

CircleCI builds have a different build context than Docker-driven local builds. Explicitly exclude vendor to avoid odd YAML front matter errors.
Disable the tests since they are generating false or low-priority defects, defer their resolution to different PR.

Get basic CircleCI builds working

---

_pages/project-setup.md

Fixes broken pa11y link on project setup page.
https://github.com/18F/development-guide/blob/master/_pages/project-setup.md

Fix Pa11y setup link

---

.circleci/config.yml

The CircleCI config we reused from the TTS handbook will erroneously flag .pngs, .pdfs as not having {{site.baseurl}}. 
For now, just ignore binary files in the check, as it's convenient in some cases to have associated images, PDFs nested under a subsection folder.

Ignore binary files in site.baseurl check

---

_pages/index.md

"/project-setup" was in the list twice, so I removed the second instance.

Remove duplicate link for project setup

---

_data/navigation.yml

https://engineering.18f.gov/security/ links to https://engineering.18f.gov/security/output_encoding/ when it should be https://engineering.18f.gov/security/output-encoding/

Update navigation.yml link

---

.circleci/config.yml
Gemfile
Gemfile.lock
_includes/components/footer--medium.html
_pages/css/architecture.md
_pages/css/naming.md
_pages/incident-reports.md
_pages/tech-leads.md

This PR adds `htmlproofer` back to the Gemfile and re-enables the CircleCI test step. It also fixes the errors. The biggest source of errors was the link to the top of the page in the shared footer. I fixed that one by adding a `data-proofer-ignore` attribute to the link, which causes htmlproofer to skip it. The other fixes were one link that no longer exists, a capitalization issue, and switching some underscores to dashes.
Closes #117

Enable htmlproofer and fix errors

---

_pages/architecture-reviews.md

Partially addresses #124 
Since the architecture reviews aren't updated, but snapshots in time, add their original publication year to provide context for their guidance.

Updates to architecture reviews

---

_pages/frontend.md
_pages/index.md

Resolves https://github.com/18F/development-guide/issues/151 by reverting #140 
Need to reconsider the removal of the frontend disciplines page:
* [18/page-redirects](https://github.com/18F/pages-redirects) was set up to "permanently" redirect `frontend.18f.gov` to `engineering.18f.gov/frontend/`
* removal was driven by outdated content about disciplines on that page and not information architecture (i.e., probably best to consider expanding hierarchy to frontend/backend/mobile/etc., rather than just the language guidance)

Revert "Remove front-end disciplines page"

---

_includes/components/tag-caution.html
_pages/javascript/frameworks.md

Makes a first pass at updating the JS frameworks page
- adds a new `Caution` tag
- adds some text at the top about also considering vanilla JS
- makes React our default
- makes Angular a suggestion, updates language to reflect Angular rather than AngularJS
- adds a "deprecated" section and puts AngularJS, Backbone, and jQuery in it
- @cantsin @hbillings ☝️ Since y'all chimed in about Backbone and jQuery, would y'all like to take a pass at some words about why we discourage those?
Will eventually close #133

Update JS framework page

---

_data/header.yml

This pull request assigns a missing `type` value for the header data.
Without a type, the base `uswds-jekyll` theme will not render a wrapping container element:
https://github.com/18F/uswds-jekyll/blob/472991d/_includes/components/header.html#L3-L9
This is also consistent with the TTS Handbook.
URL: https://handbook.tts.gsa.gov/
Code: https://github.com/18F/handbook/blob/3875342/_data/header.yml#L2
**Screenshots:**
Before|After
---|---
The text wrapping occurs because the USWDS basic header assigns a width of `10%` on the logo container. This appears to have been increased to `33%` as of USWDS v2 ([before](https://v1.designsystem.digital.gov/components/headers/basic/), [after](https://designsystem.digital.gov/components/headers/basic/)), which could be explored as a separate task.

Assign header type as "basic" for TTS Handbook consistency

---

_config.yml
assets/js/application.js
assets/js/private-eye.js

Closes #150
This pull request integrates [PrivateEye](https://github.com/18F/private-eye) to mark internal URLs as private (with a 🔒  icon).
**Screenshot:**
[👀  Live Preview](https://federalist-0fc100fe-c4d0-4b8f-bd4f-7392edd7c16d.app.cloud.gov/preview/18f/development-guide/add/private-eye/integrations/)
**Implementation Notes:**
The approach is largely inherited from [18F/handbook](https://github.com/18F/handbook), which it seeks to imitate:
- Adds the plugin script as a local asset file
- Initializes in a (new) `application.js` during `DOMContentLoaded`
There are a couple differences:
- Formatting is applied to `application.js` using Prettier (v2) with default settings
- It only includes the subset of [URLs from the handbook initialization](https://github.com/18F/handbook/blob/3875342830 …

Add PrivateEye to mark internal URLs

---

_pages/continuous-deployment.md

This is a tiny fix for a couple URLs that were present in the documentation, but not as clickable links. This adds angle-brackets to keep the URLs and make them clickable.

Add link formatting to some URLs

---

_guide/_config.yml

For consistency with the TTS branch convention for (new) repos. Related changes already complete on GitHub and Federalist.

Default branch changed from master to main

---

_guide/_pages/javascript/dependencies.md

- fixes links in the JS doc (they were links with no hrefs, so they didn't render anything)
- adds some words about configuring git and GitHub to ignore `package-lock.json` when doing diffs by setting up a `.gitattributes` file
- also adds some words about using [npm-merge-driver](https://www.npmjs.com/package/npm-merge-driver) to automatically resolve `package-lock.json` merge conflicts

Add .gitattributes tip to the Javascript guide

---

_guide/_pages/code-review.md

- add subnav
- fix broken link (resolves #85)
- simplify attribution (main credit moved to /resources/)
- remove botched checklist markup (kramdown doesn't do it well)

Minor fixes, tweaks to code review

---

_guide/_data/navigation.yml
_guide/_pages/laptop-setup.md

The laptop script has been deprecated, but the list of what it installed seems useful to have a reference to for onboarding engineers. (As was suggested in the comments of [this PR](https://github.com/18F/handbook/pull/2186).
This PR just takes the list and drops it into the engineering guide as some software suggestions, with a link to the archived laptop script for reference or in case anyone is interested in a way to setup personak dotfiles.

Add laptop setup suggestions

---

_guide/_pages/index.md

Based on feedback, clarify our classification tags as we've only applied them to portions of the guide and likely will never explicitly tag every topic, sub-section, etc.

Clarify classification tags

---

_guide/_data/navigation.yml
_guide/_pages/web-architecture.md

This page came out of discussions at Engineering Practices Guild meetings ([meeting notes](https://docs.google.com/document/d/15Yk92auwqTse1MaRzro_ChIFTm4Q8sCocsZIdY9dG94/edit?usp=sharing)) ([mural board](https://app.mural.co/t/gsa6/m/gsa6/1597938543224/007c0e0058e2299b244329b4f922151fb78722ef)) about using Single Page Applications for government websites.
The topic expanded into a general survey of static and server-rendered options, and the layers of interactivity that could sit on top of them. 
We hope to present this PR/page at a future Engineering Practices Guild meeting for discussion. This text could also use some Plain Language love in collaboration with content folks. Feedback is welcome by all!
This page was drafted by @alexsoble @adunkman @KendrickDaniel @echappen

Add page for choosing a web application architecture

---

_guide/_pages/architecture-reviews.md

This shifts the focus of the existing [Architecture Reviews](https://engineering.18f.gov/architecture-reviews/) page to not only highlight our past projects but also document an emerging practice of using Architecture Decision Records. 
I also added a quick summary of the projects to explain their context to architecture reviews, which wasn’t immediately apparent to me.
See the [Federalist preview](https://federalist-0fc100fe-c4d0-4b8f-bd4f-7392edd7c16d.app.cloud.gov/preview/18f/development-guide/add-architecture-decision-records/architecture-reviews/).

Revamp architecture reviews page to include ADRs.

---

_pages/laptop-setup.md

In 2020 GitHub launched [`gh`](https://cli.github.com/), an officially maintained easy-to-use CLI tool. The previous tool, `hub`, is now listed as "unofficial" on their repo. It is still maintained, but Github recommends using `gh` so I thought I'd add it here while still keeping `hub`. Personally, I have had a great experience with `gh`.
More information about the difference here: https://github.com/cli/cli/blob/trunk/docs/gh-vs-hub.md

Add the new GH officially maintained CLI tool to the list of laptop tools

---

_pages/architecture-reviews.md

👋 Looks like there was a refactor / reorg in the repo that moved some files around.

Fix broken link to ADR template

---

_pages/docker.md

Follow-up to https://github.com/18F/development-guide/pull/270.

link to additional Docker Hub orgs

---

_pages/project-setup.md

CodeCov is not approved for use (no GSA ATO, not in GEAR). CodeQL is approved by virtue of it being part of GitHub.

Remove CodeCov, add CodeQL on GitHub

---

_pages/code-review.md

Thought it'd be a good idea to add this resource for code reviews, since a few engineers have asked about it. 
Pa11y failures addressed in [this PR](https://github.com/18F/development-guide/pull/277)

Mention Conventional Comments syntax as a code review strategy

---

_pages/language-selection.md

It's a good joke, it's a great joke even, but the footnotes on this page are _really_ distracting.
Every time I try to read this page after I've been away from it for a while, I check the footnotes, assuming they have valuable information. They don't, but by the time I've realized this, my attention has been pulled away from what I was trying to accomplish.

Remove joke footnotes

---

_data/navigation.yml

**Description:**
Certain pages (like Tools -> Laptop Setup) don't show up in the left navigation bar highlighted as the current page being viewed. This could lead to possible confusion on where the page is actually located, but also it breaks the convention of how the other pages work within the guide.
This PR fixes it by adds in missing `/` on all the URLs in [_data/navigation.yml](_data/navigation.yml) so that the site knows where the page is in the navigation hierarchy.
**Before and After Screenshots:**

Fix left-side nav current page highlight for certain pages

---

_data/navigation.yml
_pages/books-we-have-read.md
_pages/reading-list.md

Original Slack thread is at https://gsa-tts.slack.com/archives/C02CD5VUQ/p1603474669167500
To be clear, this is not an endorsement, just a list of books that TTS folks have claimed to have read related to software development, building and engineering products. 
I decided against linking to any particular book reseller. Tracking down a good direct link each book's publisher was also a bit tricky. So in the end I only provided direct links to content that is freely available online.
`Tools` seemed to be the most appropriate, existing heading to put this list under.

Publications TTS folks have said they have read

---

_data/navigation.yml
_pages/apis.md

This PR brings in the now-archived [18F API Standards](https://github.com/18F/api-standards) repo into the guide. The new page, called **APIs**, is (for now) in the _Our Approach_ section.
Things I'd like to do before landing:
Closes #295

Add API standards

---

_data/navigation.yml
_pages/ruby.md
_pages/tests/tests.md

Addresses #205. 
I think we should add more automated testing recommendations but this creates a landing spot for that kind of documentation and addresses the original issue.

Add automated testing page and HTMLProofer

---

doc/bpdr/0003-set-criteria-for-static-site-framework.md

Creating this BPDR to continue discussion on the topic of alternative static site generators to Jekyll. The goal here is to agree on criteria, not on which alternative we should use (that'll come later). Areas needing more info are marked with **TK**.  Comments welcome!

Add BPDR for static site generator criteria

---

_data/usa_identifier.yml
_includes/footer.html

As per [digital council needs](https://gsa-tts.slack.com/archives/C018QJ2L44X/p1655234447293049), the engineering development guide should have:
* A way for someone to contact [via email](https://gsa-tts.slack.com/archives/C02UQQWDSR1/p1655316684335769?thread_ts=1655308177.072209&cid=C02UQQWDSR1) and 
* A link to the privacy policy,

add email address and privacy policy

---

_pages/accessibility-scanning.md

Several months ago while setting up GH Actions for an 11ty site, I discovered that the instructions in the handbook worked for jekyll but not for 11ty, which lacked a "detached" mode.
Using 11ty testing instructions from an example provided by @heymatthenry, I pulled out the shared configuration and then added sections with the specific instructions for jekyll and 11ty.
[Here is the page preview in Federalist](https://federalist-0fc100fe-c4d0-4b8f-bd4f-7392edd7c16d.app.cloud.gov/preview/18f/development-guide/testing-eleventy/accessibility-scanning/)
If you were tagged as a reviewer, it's only because I don't really know who is in charge of reviewing / merging things in this repo!

updates GitHub action pa11y docs for jekyll and 11ty
